#!/bin/bash
# ==========================================================
#  generate_gitignore.sh
#  Claude Gitignore Skill - by didoux
#
#  Generates a .gitignore file for your project using the
#  gitignore.io CLI tool (gi) or its web API fallback.
#
#  Usage:
#     ./scripts/generate_gitignore.sh "java,maven,docker,intellij"
# ==========================================================

set -e

TAGS="$1"

# 🧩 Validate input
if [ -z "$TAGS" ]; then
  echo "Usage: $0 \"java,maven,docker,intellij\""
  echo "Example:"
  echo "  ./scripts/generate_gitignore.sh \"java,gradle,linux,docker,intellij\""
  exit 1
fi

# 🧰 Generate .gitignore
if ! command -v gi &>/dev/null; then
  echo "⚠️  'gi' not found. Using curl fallback..."
  curl -L -s "https://www.toptal.com/developers/gitignore/api/${TAGS}" -o .gitignore
else
  echo "🛠️  Using gitignore.io CLI (gi) to generate .gitignore..."
  gi "${TAGS}" > .gitignore
fi

# 🧾 Verify .gitignore was created
if [ -s .gitignore ]; then
  echo "# Generated by Claude Gitignore Skill on $(date)" | cat - .gitignore > temp && mv temp .gitignore
  echo "✅ .gitignore generated successfully for: ${TAGS}"
  echo "📄 Preview (first 10 lines):"
  echo "------------------------------------"
  head -n 10 .gitignore
  echo "------------------------------------"
else
  echo "❌ Failed to generate .gitignore file."
  exit 1
fi
